pPacketData free bug resolved
NVIDIA/VideoProcessingFramework pull request #206
Opened 2021-05-09 07:19 UTC by vtpl1

@rarzumanyan,
Putting `pPacketData = Buffer::MakeOwnMem(sizeof(PacketData));` instead of `pPacketData = Buffer::MakeOwnMem(1U);` solved the issue.

I am not sure why it was like `pPacketData = Buffer::MakeOwnMem(1U);` in the first place.
BR,
Monotosh

2021-05-11 06:01 UTC, rarzumanyan requested changes
Hi @vtpl1 
Thanks for the PR!

Could you please clean up the patch? `Buffer::MakeOwnMem()` fix makes total sense, but other changes are IMO irrelevant.

2021-05-11 06:36 UTC, vtpl1 commented on PyNvCodec/TC/inc/MemoryInterfaces.hpp
> -  bool own_memory = true;
By default no memory is associated so why to own a NULL memory?
Though it does not solve the bug.

2021-05-11 06:44 UTC, rarzumanyan commented on PyNvCodec/TC/inc/MemoryInterfaces.hpp
> -  bool own_memory = true;
@vtpl1 

Yes, you're right about that - by default `Buffer` doesn't have any memory allocated so changing the default value won't affect the behavior.

In order to minimize the amount of changes to the code it's kinda "usual practice" to change code only if it's required to fix something or add new feature. Following this approach a person who sees your patch with "fixing pPacketData bug"-like commit message will have a good insight on what does the patch do. They would not probably expect this to introduce changes to one of the core library headers, right?

2021-05-12 06:53 UTC, vtpl1 commented
@rarzumanyan ,
Incorporated the changes,
But I am not sure why MuxFrame removal is showing as my commit.

2021-05-12 10:41 UTC, rarzumanyan commented
@vtpl1 

Unfortunately the PR looks smashed and it contain previous patches as well (7 files modified overall). 
That could probably happen because of force push.
Could you just create a new PR with only ` PyNvCodec/TC/src/Tasks.cpp` file modified?

2021-05-12 10:55 UTC, vtpl1 commented
Yes, that is what I feel, can I include the copyright notice for other files for older PR s?

2021-05-12 11:02 UTC, rarzumanyan commented
> 
> 
> @rarzumanyan
> Yes, that is what I feel, can I include the copyright notice for other files for older PR s?

I assume we can do as follows: please add your company name to the file which is modified by your latest PR and meanwhile I will consult with our legals if copyright can be added to the files affected by your previous contributions. 

Does this approach make sense to you?

2021-05-12 11:23 UTC, vtpl1 commented
ok sournds good

2021-05-12 11:23 UTC, closed without merging